"""Phase 2 smoke — per-question WS protocol with real APIs.

Walks through:
- Initiate (real risk classifier picks the tier)
- Receive ready event with questions list (real Claude generation)
- Send tagged audio chunks per question + answer_end
- Receive per-question hume_partial events (real Hume per Q)
- For HIGH_RISK: also send a client_gemini summary
- Receive decision (real Claude with per-Q buckets)
"""

from __future__ import annotations

import asyncio
import base64
import json
import time

import httpx
import websockets

BASE = "http://localhost:8000"
WS_BASE = "ws://localhost:8000"


def silent_pcm(seconds: float = 3.0) -> bytes:
    """16kHz mono PCM16 silence."""
    return bytes(int(seconds * 16000) * 2)


async def run_one(label: str, merchant: str, amount: float, send_video: bool):
    print(f"\n=== {label}: {merchant} €{amount}")
    async with httpx.AsyncClient(timeout=120.0) as client:
        # Force MOCK off (Phase 2 needs real APIs to be meaningful)
        await client.post(f"{BASE}/api/mock/toggle", json={"mock": False})
        r = await client.post(
            f"{BASE}/api/transaction/initiate",
            json={"amount_eur": amount, "merchant": merchant},
        )
        body = r.json()
        tier = body["tier"]
        print(f"  Tier: {tier}, Reputation: {body['merchant_reputation']}")

        if tier == "NO_RISK":
            print("  -> auto-approved, no verification")
            return

        ver_id = body["verification_id"]
        t0 = time.perf_counter()
        async with websockets.connect(f"{WS_BASE}/ws/verify/{ver_id}") as ws:
            ready = json.loads(await ws.recv())
            assert ready["type"] == "ready"
            questions = ready["questions"]
            print(f"  Questions ({len(questions)} generated by Claude):")
            for q in questions:
                print(f"    [{q['purpose']:15}] {q['text']}")

            # Per-question loop
            hume_partials = []
            for q in questions:
                # Send a chunk of silence as the "answer"
                pcm = silent_pcm(2.5)
                await ws.send(json.dumps({
                    "type": "audio_chunk",
                    "q_id": q["id"],
                    "data": base64.b64encode(pcm).decode(),
                }))
                await ws.send(json.dumps({
                    "type": "answer_end",
                    "q_id": q["id"],
                    "transcript": "",
                }))
                # Wait for hume_partial for this question
                while True:
                    msg = json.loads(await ws.recv())
                    if msg["type"] == "hume_partial" and msg.get("q_id") == q["id"]:
                        hume_partials.append(msg)
                        scores = msg["scores"]
                        delta = msg.get("delta_vs_baseline")
                        if delta is None:
                            tail = "baseline"
                        else:
                            tail = f"Δfear={delta['fear']:.2f} Δdistress={delta['distress']:.2f}"
                        print(f"    -> hume[{q['id']}]: calm={scores['calmness']:.2f} "
                              f"fear={scores['fear']:.2f} distress={scores['distress']:.2f} "
                              f"hint={scores['verdict_hint']} {tail}")
                        break

            if send_video:
                # One tiny black frame is enough to trigger HIGH_RISK pathway.
                tiny_jpeg = bytes.fromhex(
                    "ffd8ffe000104a46494600010100000100010000ffdb0043"
                    "000302020302020303030304030304050805050404050a07"
                    "0706080c0a0c0c0b0a0b0b0d0e12100d0e110e0b0b1016"
                    "161113141513ffd9"
                )
                await ws.send(json.dumps({
                    "type": "video_frame",
                    "data": base64.b64encode(tiny_jpeg).decode(),
                }))
                # Send a synthetic frontend-Gemini summary (since the test isn't
                # actually a browser running Gemini Live).
                await ws.send(json.dumps({
                    "type": "client_gemini",
                    "summary": {
                        "location_type": "public_unfamiliar",
                        "duress_signals": ["second_person_visible"],
                        "confidence": 0.78,
                        "raw_text": "Smoke test: simulated frontend Gemini summary.",
                        "service_available": True,
                    },
                }))
                # Optional: read the echoed gemini_partial
                try:
                    msg = json.loads(await asyncio.wait_for(ws.recv(), timeout=2.0))
                    if msg["type"] == "gemini_partial":
                        s = msg["summary"]
                        print(f"    -> gemini echo: {s['location_type']}, signals={s['duress_signals']}")
                except asyncio.TimeoutError:
                    pass

            await ws.send(json.dumps({"type": "end"}))

            # Drain remaining messages until decision
            decision = None
            while True:
                msg = json.loads(await ws.recv())
                if msg["type"] == "decision":
                    decision = msg
                    break

        elapsed = int((time.perf_counter() - t0) * 1000)
        print(f"  Verdict: {decision['verdict']}")
        print(f"  Rationale: {decision['rationale']}")
        print(f"  Wall time: {elapsed}ms")


async def main():
    # Prep — make sure mock is off
    async with httpx.AsyncClient(timeout=10.0) as client:
        await client.post(f"{BASE}/api/mock/toggle", json={"mock": False})

    await run_one("MID_RISK FastWire", "FastWire", 600.0, send_video=False)
    await run_one("HIGH_RISK Unknown LLP", "Unknown LLP", 5000.0, send_video=True)


if __name__ == "__main__":
    asyncio.run(main())
